# Generated by the reproducible-paper-artefacts skill. Edit freely; the rules
# below are a worked skeleton, not a fixed contract.

from glob import glob
from pathlib import Path
import os
import subprocess
import sys

ART = "paper/artefacts"
NOTES = "paper/notes/artefacts"

# Python scripts import the helpers with `import artefacts`. Snakemake runs each
# script under its own interpreter and puts only the script's folder on
# sys.path, so the helper folder goes on PYTHONPATH here, where `make` and a
# bare `snakemake` both pass. That interpreter is also where a Python rule's
# packages must be installed. Here it is the project environment, .venv, which
# `uv sync` builds from pyproject.toml and uv.lock, and the Makefile runs the
# Snakemake installed there.
os.environ["PYTHONPATH"] = os.pathsep.join(
    p for p in (str(Path("py/lib").resolve()), os.environ.get("PYTHONPATH")) if p
)

# The registry: every artefact the manuscript uses. A name here without a rule
# below fails at once with MissingRuleException, so this list is safe to treat
# as the registry.
NUMBERS: list[str] = []
FIGURES = ["fits", "convergence"]      # Figures 1 and 2
TABLES = ["empirical"]                 # Table 1

# Exploratory output. Deliberately not part of `rule all`: a manuscript build
# should not drag along months of abandoned exploration. These two are the
# experiments the referee asked for (comment 7 of the first report).
NOTES_NUMBERS: list[str] = []
NOTES_FIGURES = ["noise-sweep", "dimension-sweep"]
NOTES_TABLES: list[str] = []


def lib(*dirs):
    """Every file under these topic directories, as rule inputs.

    Snakemake's `code` rerun trigger hashes the script file and nothing it
    sources or imports. Change a function in R/lib/estimate and the script
    hashes the same, so Snakemake reports the artefact as up to date when it is
    not. A false-fresh number is worse than no tracking at all, because it is
    the kind of wrong you stop checking for.

    Declaring the directory fixes that without per-file bookkeeping. New helper
    files are picked up automatically, and invalidation is coarse in the safe
    direction: editing any estimation helper marks every fit stale, and nothing
    that read a file is ever missed.

    The lever on precision is directory structure. If R/lib/estimate is too
    blunt, split it into estimate/ipw and estimate/tmle and have each rule
    depend on what it uses.
    """
    out = []
    for d in dirs:
        # A single file is a legitimate argument. Globbing "file.R/**/*" matches
        # nothing, so without this a lib("R/lib/artefacts.R") would silently
        # declare no dependency at all, which is the exact silent
        # under-declaration this helper exists to prevent.
        if Path(d).is_file():
            out.append(d)
            continue
        for f in glob(f"{d}/**/*", recursive=True):
            q = Path(f)
            if not q.is_file():
                continue
            # Compiled bytecode and editor droppings are not source. They also
            # change every time the interpreter runs, so declaring them would
            # mark artefacts stale for no reason and train you to ignore the
            # staleness report.
            if any(part.startswith(".") or part == "__pycache__" for part in q.parts):
                continue
            if q.suffix in {".pyc", ".pyo", ".so", ".o", ".rdb", ".rdx"}:
                continue
            out.append(f)
    return sorted(out)


# Helper code, by topic. Each rule declares what its script imports, and the
# Table 1 rules declare single files, because the fast cells take two hours and
# should not rerun after an edit they do not read.
KRR = lib("py/lib/kernel_ridge")                        # HAR and the other kernel ridge methods
HAL = lib("py/lib/highly_adaptive_regression.py")       # HAL
T1 = "py/lib/table1"
TABLE1_CELL = lib(f"{T1}/__init__.py", f"{T1}/design.py", f"{T1}/data.py", f"{T1}/cell.py")
SIM = lib("py/lib/sim") + KRR + HAL                     # the simulations; cheap, so declared broadly
DISPLAY = lib("py/lib/display", "py/lib/artefacts.py")  # summaries, figures and tables


# ---------------------------------------------------------------------------
# The design: which cells exist. The settings inside a cell (seeds, splits,
# learners) are in py/lib, where a change reruns the cells that read them.

DATA = "data/uci"   # the UCI csv files; data/README.md says where they come from

# Table 1, with the datasets in the order of the paper's rows.
TABLE1_DATASETS = [
    "power", "yacht", "concrete", "energy", "kin8nm", "protein",
    "wine", "boston", "naval", "yearmsd", "slice",
]
TABLE1_HAL_DATASETS = ["yacht", "energy", "boston", "concrete"]
TABLE1_REPS = list(range(5))
TABLE1_METHODS = [
    "HAR", "HAL", "Mixed Sobolev KRR", "Radial Basis KRR", "Random Forest",
    "Ridge Regression",
]

# Figure 2 and the noise sweep are one simulation over (sigma, n).
CONVERGENCE_N = [50, 125, 200, 300, 400, 600]
CONVERGENCE_SIGMA = ["0.1"]            # Figure 2
NOISE_SIGMA = ["0.1", "0.5", "1.0"]    # the noise sweep

# The dimension sweep.
DIMENSION_DGPS = ["interaction", "additive"]
DIMENSION_P = [5, 8, 10, 15, 20, 30]

wildcard_constraints:
    dataset=r"[a-z0-9]+",
    rep=r"\d+",
    sigma=r"[0-9.]+",
    n=r"\d+",
    dgp=r"[a-z]+",
    p=r"\d+",


onstart:
    # The Makefile already ran this, with a friendlier message. Running it again
    # here is what closes the bypass: a bare `snakemake` gets guarded too. With
    # no tier given the strictest one applies, so the bypass fails closed.
    tier = config.get("tier", "paper")
    result = subprocess.run(
        [sys.executable, "tools/build_guard.py", "--tier", tier],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.exit(result.stdout + result.stderr)


onsuccess:
    # Collapse the per-rule provenance sidecars into BUILD.json. It lives here
    # rather than in the Makefile so that a bare `snakemake` produces exactly
    # the same result, which leaves `make` as convenience rather than as a step
    # you can forget.
    subprocess.run([sys.executable, "tools/record_provenance.py", "--merge"])


onerror:
    # A build that fails part way has still written some artefacts, and
    # BUILD.json should describe them.
    subprocess.run([sys.executable, "tools/record_provenance.py", "--merge"])


rule all:
    input:
        expand(f"{ART}/numbers/{{u}}.tex", u=NUMBERS),
        expand(f"{ART}/figures/{{f}}.pdf", f=FIGURES),
        expand(f"{ART}/tables/{{t}}.tex", t=TABLES),
        *([f"{ART}/artefacts.tex"] if NUMBERS else []),


rule notes:
    input:
        expand(f"{NOTES}/numbers/{{u}}.tex", u=NOTES_NUMBERS),
        expand(f"{NOTES}/figures/{{f}}.pdf", f=NOTES_FIGURES),
        expand(f"{NOTES}/tables/{{t}}.tex", t=NOTES_TABLES),


rule artefacts_tex:
    """One \\input line for main.tex, regenerated as numbers come and go.

    The preamble says \\input{artefacts/artefacts.tex} once and never changes.
    """
    input:
        expand(f"{ART}/numbers/{{u}}.tex", u=NUMBERS),
    output:
        f"{ART}/artefacts.tex",
    run:
        lines = ["% Generated. Do not edit.", ""]
        lines += ["\\input{artefacts/numbers/%s}" % Path(p).name for p in sorted(input)]
        Path(output[0]).write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Table 1 (tab:empirical): the test RMSE of six methods on eleven UCI datasets.
# The cells write results/, and the table reads them, so a change to the
# table's format reruns no fit. Each cell job takes every core it is given.

rule table1_cell:                  # expensive: about two hours for all 55 cells
    input:
        data=f"{DATA}/{{dataset}}.csv",
        helpers=KRR + TABLE1_CELL + lib(f"{T1}/learners.py"),
    output:
        "results/table1/{dataset}/rep{rep}.csv",
    threads: workflow.cores
    script: "py/table1_cell.py"


rule table1_hal_cell:              # cheap: seconds per cell, about a minute for all 20
    input:
        data=f"{DATA}/{{dataset}}.csv",
        helpers=HAL + TABLE1_CELL + lib(f"{T1}/hal.py"),
    output:
        "results/table1/{dataset}/rep{rep}-hal.csv",
    threads: workflow.cores
    script: "py/table1_hal_cell.py"


rule table_empirical:
    input:
        cells=expand("results/table1/{dataset}/rep{rep}.csv",
                     dataset=TABLE1_DATASETS, rep=TABLE1_REPS),
        hal=expand("results/table1/{dataset}/rep{rep}-hal.csv",
                   dataset=TABLE1_HAL_DATASETS, rep=TABLE1_REPS),
        helpers=DISPLAY,
    output:
        f"{ART}/tables/empirical.tex",
    params:
        datasets=TABLE1_DATASETS,
        methods=TABLE1_METHODS,
    script: "py/table_empirical.py"


# ---------------------------------------------------------------------------
# Figure 1 (fig:fits): the fits of six methods on one-dimensional data.

rule sim_fits:
    input:
        helpers=SIM,
    output:
        "results/fits/predictions.csv",
    threads: workflow.cores
    script: "py/sim_fits.py"


rule fig_fits:
    input:
        predictions="results/fits/predictions.csv",
        helpers=DISPLAY,
    output:
        f"{ART}/figures/fits.pdf",
    script: "py/fig_fits.py"


# ---------------------------------------------------------------------------
# Figure 2 (fig:convergence) and the noise sweep share one simulation, whose
# cells are (sigma, n). Figure 2 reads the cells at sigma = 0.1.

rule sim_convergence:
    input:
        helpers=SIM,
    output:
        "results/convergence/sigma{sigma}/n{n}.csv",
    threads: workflow.cores
    script: "py/sim_convergence.py"


rule fig_convergence:
    input:
        cells=expand("results/convergence/sigma{sigma}/n{n}.csv",
                     sigma=CONVERGENCE_SIGMA, n=CONVERGENCE_N),
        helpers=DISPLAY,
    output:
        f"{ART}/figures/convergence.pdf",
    script: "py/fig_convergence.py"


rule fig_noise_sweep:
    input:
        cells=expand("results/convergence/sigma{sigma}/n{n}.csv",
                     sigma=NOISE_SIGMA, n=CONVERGENCE_N),
        helpers=DISPLAY,
    output:
        f"{NOTES}/figures/noise-sweep.pdf",
    script: "py/fig_noise_sweep.py"


# ---------------------------------------------------------------------------
# The dimension sweep: HAR and mixed Sobolev KRR against the other methods the
# referee asked for, on two DGPs, as the number of covariates grows.

rule sim_dimension:
    input:
        helpers=SIM,
    output:
        "results/dimension/{dgp}/p{p}.csv",
    threads: workflow.cores
    script: "py/sim_dimension.py"


rule fig_dimension_sweep:
    input:
        cells=expand("results/dimension/{dgp}/p{p}.csv", dgp=DIMENSION_DGPS, p=DIMENSION_P),
        helpers=DISPLAY,
    output:
        f"{NOTES}/figures/dimension-sweep.pdf",
    script: "py/fig_dimension_sweep.py"
