# Generated by the reproducible-paper-artefacts skill. Edit freely; the rules
# below are a worked skeleton, not a fixed contract.

from glob import glob
from pathlib import Path
import os
import subprocess
import sys

ART = "paper/artefacts"
NOTES = "paper/notes/artefacts"

# Python scripts import the helpers with `import artefacts`. Snakemake runs each
# script under its own interpreter and puts only the script's folder on
# sys.path, so the helper folder goes on PYTHONPATH here, where `make` and a
# bare `snakemake` both pass. That interpreter is also where a Python rule's
# packages must be installed. Here it is the project environment, .venv, which
# `uv sync` builds from pyproject.toml and uv.lock, and the Makefile runs the
# Snakemake installed there.
os.environ["PYTHONPATH"] = os.pathsep.join(
    p for p in (str(Path("py/lib").resolve()), os.environ.get("PYTHONPATH")) if p
)

# The registry: every artefact the manuscript uses. A name here without a rule
# below fails at once with MissingRuleException, so this list is safe to treat
# as the registry.
NUMBERS = ["kernel-scale",             # the scale of the plain HAR kernel matrix
           "empirical",                # the settings of the estimators and of Table 1
           "fits",                     # the settings of Figure 1
           "depth"]                    # the settings of the depth figure
FIGURES = ["fits", "convergence",      # Figures 1 and 2
           "depth"]                    # cross-validated error against the depth
TABLES = ["empirical", "runtime",      # Table 1 (relative test MSE) and the fit times
          "empirical-full",            # the same two tables in the appendix, with
          "runtime-full"]              # the additional comparators

# Exploratory output. Deliberately not part of `rule all`: a manuscript build
# should not drag along months of abandoned exploration. These two are the
# experiments the referee asked for (comment 7 of the first report).
NOTES_NUMBERS = ["sobolev-mars", "sobolev-mars-fits"]   # notes/sobolev-mars.tex
NOTES_FIGURES = ["noise-sweep", "dimension-sweep",
                 "sobolev-mars-fits"]                  # notes/sobolev-mars.tex
NOTES_TABLES = ["sobolev-mars-rmse", "sobolev-mars-runtime",
                "sobolev-mars-ratios"]                 # notes/sobolev-mars.tex


def lib(*dirs):
    """Every file under these topic directories, as rule inputs.

    Snakemake's `code` rerun trigger hashes the script file and nothing it
    sources or imports. Change a function in R/lib/estimate and the script
    hashes the same, so Snakemake reports the artefact as up to date when it is
    not. A false-fresh number is worse than no tracking at all, because it is
    the kind of wrong you stop checking for.

    Declaring the directory fixes that without per-file bookkeeping. New helper
    files are picked up automatically, and invalidation is coarse in the safe
    direction: editing any estimation helper marks every fit stale, and nothing
    that read a file is ever missed.

    The lever on precision is directory structure. If R/lib/estimate is too
    blunt, split it into estimate/ipw and estimate/tmle and have each rule
    depend on what it uses.
    """
    out = []
    for d in dirs:
        # A single file is a legitimate argument. Globbing "file.R/**/*" matches
        # nothing, so without this a lib("R/lib/artefacts.R") would silently
        # declare no dependency at all, which is the exact silent
        # under-declaration this helper exists to prevent.
        if Path(d).is_file():
            out.append(d)
            continue
        for f in glob(f"{d}/**/*", recursive=True):
            q = Path(f)
            if not q.is_file():
                continue
            # Compiled bytecode and editor droppings are not source. They also
            # change every time the interpreter runs, so declaring them would
            # mark artefacts stale for no reason and train you to ignore the
            # staleness report.
            if any(part.startswith(".") or part == "__pycache__" for part in q.parts):
                continue
            if q.suffix in {".pyc", ".pyo", ".so", ".o", ".rdb", ".rdx"}:
                continue
            out.append(f)
    return sorted(out)


# Helper code, by topic. Each rule declares what its script imports, and the
# Table 1 rules declare single files, because the fast cells take two hours and
# should not rerun after an edit they do not read.
KRR = lib("py/lib/kernel_ridge")                        # HAR and the other kernel ridge methods
HAL = lib("py/lib/highly_adaptive_regression.py")       # HAL
T1 = "py/lib/table1"
TABLE1_FIT = lib(f"{T1}/__init__.py", f"{T1}/design.py", f"{T1}/data.py", f"{T1}/fit.py")
SIM = lib("py/lib/sim") + KRR + HAL                     # the simulations; cheap, so declared broadly
DEMO = lib("py/lib/sim/__init__.py", "py/lib/sim/design.py", "py/lib/sim/dgps.py", "py/lib/sim/demo.py")
DISPLAY = lib("py/lib/display", "py/lib/artefacts.py")  # summaries, figures and tables

# The estimators of Section 4, one module each in py/lib/estimators. Each rule
# that fits an estimator declares that estimator's code and nothing else, so an
# edit to one estimator reruns only its fits.
EST = "py/lib/estimators"
EST_BASE = lib(f"{EST}/__init__.py", f"{EST}/folds.py")
KPATH = EST_BASE + KRR + lib(f"{EST}/kernel_path.py")
ESTIMATOR_CODE = {
    "har": KPATH + lib(f"{EST}/depths.py", f"{EST}/har.py"),
    "har1": KPATH + lib(f"{EST}/depths.py", f"{EST}/har1.py"),
    "mixed_sobolev": KPATH + lib(f"{EST}/mixed_sobolev.py"),
    "rbf": KPATH + lib(f"{EST}/rbf.py"),
    "hal": EST_BASE + HAL + lib(f"{EST}/hal.py"),
    "rf": EST_BASE + lib(f"{EST}/rf.py"),
    "gbt": EST_BASE + lib(f"{EST}/gbt.py"),
    "mlp": EST_BASE + lib(f"{EST}/mlp.py"),
    "enet": EST_BASE + lib(f"{EST}/enet.py"),
}
ESTIMATORS = list(ESTIMATOR_CODE)   # the order of Section 4

# The four estimators that notes/sobolev-mars.tex adds, one module each in
# py/lib/estimators: kernel ridge with the anchored mixed Sobolev kernels, the
# limits of HAR and first-order HAR with their depth weights, kernel ridge with
# the first-order mixed Sobolev kernel of the usual norm, and MARS. They are
# not in estimators.SLUGS, the paper's list, which every Table 1 fit reads, so
# their rules run py/more_fits.py, which registers them first. pymars needs a
# newer scikit-learn than the main environment pins, so the MARS fits run
# under the interpreter of envs/mars, and they declare its lock file.
MORE_BASE = lib(f"{EST}/more.py", "py/more_fits.py")
SOBOLEV = KPATH + lib(f"{EST}/sobolev_kernels.py")
MORE_CODE = {
    "anchored_sobolev": SOBOLEV + lib(f"{EST}/depths.py", f"{EST}/anchored_sobolev.py"),
    "mixed_sobolev1": SOBOLEV + lib(f"{EST}/mixed_sobolev1.py"),
    "anchored_sobolev1": SOBOLEV + lib(f"{EST}/depths.py", f"{EST}/anchored_sobolev1.py"),
    "mars": EST_BASE + lib(f"{EST}/depths.py", f"{EST}/mars.py", "envs/mars/pyproject.toml",
                           "envs/mars/uv.lock"),
}
MORE = list(MORE_CODE)
MARS_PYTHON = "envs/mars/.venv/bin/python"

# The estimators that the note added second, at the user's request: the
# usual-norm mixed Sobolev kernels with HAR's depth weights, of orders 0 and 1,
# so that the comparison of the anchored and the usual-norm kernels is not
# also one of depth tuning. They have their own registry and fit script
# (py/added_fits.py), so that the fits of MORE, which read estimators/more.py
# and py/more_fits.py, do not rerun.
DEPTH_BASE = lib(f"{EST}/more_depth.py", "py/added_fits.py")
DEPTH_SOBOLEV = SOBOLEV + lib(f"{EST}/sobolev_depth.py", f"{EST}/depths.py")
DEPTH_CODE = {
    "mixed_sobolev_depth": DEPTH_SOBOLEV + lib(f"{EST}/mixed_sobolev_depth.py"),
    "mixed_sobolev1_depth": DEPTH_SOBOLEV + lib(f"{EST}/mixed_sobolev1_depth.py"),
}
DEPTH = list(DEPTH_CODE)

# The note's columns and panels: each HAR next to its limit kernel and the two
# kernels of the usual norm, with and without depth, then the other estimators
# in the order of Section 4.
SM_METHODS = ["har", "anchored_sobolev", "mixed_sobolev_depth", "mixed_sobolev",
              "har1", "anchored_sobolev1", "mixed_sobolev1_depth", "mixed_sobolev1",
              "rbf", "hal", "mars", "rf", "gbt", "mlp", "enet"]

# The paper's Section 4: the estimators of the main text, in its order, and all
# of them with the additional comparators of the appendix ("Additional
# Empirical Results"), with the methods of one kind together. Mixed Sobolev KRR
# is the version with depth tuning; the plain kernel (mixed_sobolev) is no
# longer in the paper. The first-order estimators (har1, mixed_sobolev1_depth)
# left the paper in October 2026 with the rest of higher-order HAR; their fits
# stay for paper/notes/higher-order-har.tex.
PAPER_MAIN = ["har", "mixed_sobolev_depth", "rbf", "hal", "rf", "enet"]
PAPER_ALL = ["har", "mixed_sobolev_depth", "rbf", "hal", "mars", "rf", "gbt", "mlp", "enet"]
# The paper's names for the estimators whose module names them otherwise.
PAPER_NAMES = {"mixed_sobolev_depth": "Mixed Sobolev KRR",
               "mixed_sobolev1_depth": "1st-order Mixed Sobolev KRR"}


# ---------------------------------------------------------------------------
# The design: which cells exist. The settings inside a cell (seeds, splits,
# learners) are in py/lib, where a change reruns the cells that read them.

DATA = "data/uci"   # the UCI csv files; data/README.md says where they come from

# Table 1, with the datasets in the order of the paper's rows.
TABLE1_DATASETS = [
    "power", "yacht", "concrete", "energy", "kin8nm", "protein",
    "wine", "boston", "naval", "yearmsd", "slice",
]
TABLE1_REPS = list(range(5))
# The fits that are not run. HAL's implementation handles at most 63
# covariates. A first-order HAR kernel on slice takes minutes to build on one
# core, so even its first depth would take the fit far past its time budget.
TABLE1_SKIP = {("yearmsd", "hal"), ("slice", "hal"), ("slice", "har1")}


def fits_of(methods):
    """The (dataset, method) cells of Table 1 for these methods, less the skipped ones."""
    return [(d, m) for d in TABLE1_DATASETS for m in methods if (d, m) not in TABLE1_SKIP]


TABLE1_FITS = fits_of(ESTIMATORS)   # the nine estimators fit first; the note reads these
PAPER_FITS = fits_of(PAPER_ALL)     # what the paper's tables read


def table1_files(kind, cells=None):
    """The result or tuning file of every Table 1 fit of these cells (default: the paper's)."""
    suffix = "" if kind == "result" else "-tuning"
    cells = PAPER_FITS if cells is None else cells
    return [f"results/table1/{d}/{m}/rep{r}{suffix}.csv" for d, m in cells for r in TABLE1_REPS]

# Figure 2 and the noise sweep are one simulation over (sigma, n).
CONVERGENCE_N = [50, 125, 200, 300, 400, 600]
CONVERGENCE_SIGMA = ["0.1"]            # Figure 2
NOISE_SIGMA = ["0.1", "0.5", "1.0"]    # the noise sweep

# The dimension sweep.
DIMENSION_DGPS = ["interaction", "additive"]
DIMENSION_P = [5, 8, 10, 15, 20, 30]

# Every job runs on one thread: the linear algebra (Accelerate, OpenBLAS, MKL),
# OpenMP and numba. Jobs run in parallel, one to a core, so the time of each
# fit is the time of one core, and the times of the estimators compare.
for _v in ["VECLIB_MAXIMUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS",
           "OMP_NUM_THREADS", "NUMBA_NUM_THREADS"]:
    os.environ[_v] = "1"

wildcard_constraints:
    dataset=r"[a-z0-9]+",
    method=r"[a-z0-9_]+",
    rep=r"\d+",
    sigma=r"[0-9.]+",
    n=r"\d+",
    dgp=r"[a-z]+",
    p=r"\d+",


onstart:
    # The Makefile already ran this, with a friendlier message. Running it again
    # here is what closes the bypass: a bare `snakemake` gets guarded too. With
    # no tier given the strictest one applies, so the bypass fails closed.
    tier = config.get("tier", "paper")
    result = subprocess.run(
        [sys.executable, "tools/build_guard.py", "--tier", tier],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        sys.exit(result.stdout + result.stderr)


onsuccess:
    # Collapse the per-rule provenance sidecars into BUILD.json. It lives here
    # rather than in the Makefile so that a bare `snakemake` produces exactly
    # the same result, which leaves `make` as convenience rather than as a step
    # you can forget.
    subprocess.run([sys.executable, "tools/record_provenance.py", "--merge"])


onerror:
    # A build that fails part way has still written some artefacts, and
    # BUILD.json should describe them.
    subprocess.run([sys.executable, "tools/record_provenance.py", "--merge"])


rule all:
    input:
        expand(f"{ART}/numbers/{{u}}.tex", u=NUMBERS),
        expand(f"{ART}/figures/{{f}}.pdf", f=FIGURES),
        expand(f"{ART}/tables/{{t}}.tex", t=TABLES),
        *([f"{ART}/artefacts.tex"] if NUMBERS else []),


rule notes:
    input:
        expand(f"{NOTES}/numbers/{{u}}.tex", u=NOTES_NUMBERS),
        expand(f"{NOTES}/figures/{{f}}.pdf", f=NOTES_FIGURES),
        expand(f"{NOTES}/tables/{{t}}.tex", t=NOTES_TABLES),


rule artefacts_tex:
    """One \\input line for main.tex, regenerated as numbers come and go.

    The preamble says \\input{artefacts/artefacts.tex} once and never changes.
    """
    input:
        expand(f"{ART}/numbers/{{u}}.tex", u=NUMBERS),
    output:
        f"{ART}/artefacts.tex",
    run:
        lines = ["% Generated. Do not edit.", ""]
        lines += ["\\input{artefacts/numbers/%s}" % Path(p).name for p in sorted(input)]
        Path(output[0]).write_text("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Table 1 (tab:empirical) and the fit times (tab:runtime): nine estimators on
# eleven UCI datasets. Each fit is one job, on one thread: one estimator, one
# dataset and one repetition. The fits write results/, and the tables read it,
# so a change to a table's format reruns no fit, and a change to one
# estimator reruns only its fits.

def _fit_code(wc):
    return ESTIMATOR_CODE[wc.method] + TABLE1_FIT


rule table1_fit:
    input:
        data=f"{DATA}/{{dataset}}.csv",
        helpers=_fit_code,
    output:
        result="results/table1/{dataset}/{method}/rep{rep}.csv",
        tuning="results/table1/{dataset}/{method}/rep{rep}-tuning.csv",
    wildcard_constraints:
        method="|".join(m for m in ESTIMATORS if m != "har1"),
    threads: 1
    script: "py/table1_fit.py"


# First-order HAR has the longest fits, so its jobs start first.
use rule table1_fit as table1_fit_har1 with:
    wildcard_constraints:
        method="har1",
    priority: 10


rule table_empirical:
    input:
        results=table1_files("result"),
        tunings=table1_files("tuning"),
        helpers=DISPLAY,
    output:
        mse=f"{ART}/tables/empirical.tex",
        runtime=f"{ART}/tables/runtime.tex",
        mse_full=f"{ART}/tables/empirical-full.tex",
        runtime_full=f"{ART}/tables/runtime-full.tex",
        numbers=f"{ART}/numbers/empirical.tex",
    params:
        datasets=TABLE1_DATASETS,
        main=PAPER_MAIN,
        methods=PAPER_ALL,
        names=PAPER_NAMES,
    script: "py/table_empirical.py"


# ---------------------------------------------------------------------------
# The depth figure (fig:depth): the cross-validated error of HAR and of mixed
# Sobolev KRR at every depth of the depth path, with no early stopping, on the
# training part and the folds of each Table 1 fit. One job per dataset, method
# and repetition, on one thread. It fits the estimator's own code with its
# patience removed, so each curve is the one that the early-stopped walk of the
# Table 1 fit follows until it stops.

DEPTH_CURVE_METHODS = ["har", "mixed_sobolev_depth"]
DEPTH_CURVE_CODE = {
    "har": ESTIMATOR_CODE["har"],
    "mixed_sobolev_depth": DEPTH_CODE["mixed_sobolev_depth"],
}


rule depth_curve:
    input:
        data=f"{DATA}/{{dataset}}.csv",
        helpers=lambda wc: DEPTH_CURVE_CODE[wc.method] + lib(f"{EST}/more_depth.py") + TABLE1_FIT,
    output:
        "results/depth/{dataset}/{method}/rep{rep}.csv",
    wildcard_constraints:
        method="|".join(DEPTH_CURVE_METHODS),
    threads: 1
    script: "py/depth_curve.py"


# The curves of the two widest datasets take the longest, so their jobs start first.
use rule depth_curve as depth_curve_wide with:
    wildcard_constraints:
        dataset="slice|yearmsd",
        method="|".join(DEPTH_CURVE_METHODS),
    priority: 10

ruleorder: depth_curve_wide > depth_curve


rule fig_depth:
    input:
        curves=expand("results/depth/{dataset}/{method}/rep{rep}.csv", dataset=TABLE1_DATASETS,
                      method=DEPTH_CURVE_METHODS, rep=TABLE1_REPS),
        helpers=DISPLAY,
    output:
        figure=f"{ART}/figures/depth.pdf",
        numbers=f"{ART}/numbers/depth.tex",
    params:
        datasets=TABLE1_DATASETS,
        methods=DEPTH_CURVE_METHODS,
        names=PAPER_NAMES,
    script: "py/fig_depth.py"


# ---------------------------------------------------------------------------
# The scale of the plain HAR kernel matrix (Section "Sectional Weights"): its
# largest, smallest and largest off-diagonal elements for one draw of
# Unif([0,1]^200) points. It builds one kernel, in seconds. The script imports
# the kernels through the package, so it reads these files and no others.

rule kernel_scale:
    input:
        helpers=lib(
            "py/lib/kernel_ridge/__init__.py", "py/lib/kernel_ridge/kernel_ridge.py",
            "py/lib/kernel_ridge/kernels.py", "py/lib/kernel_ridge/timer.py",
            "py/lib/artefacts.py",
        ),
    output:
        f"{ART}/numbers/kernel-scale.tex",
    script: "py/kernel_scale.py"


# ---------------------------------------------------------------------------
# Figure 1 (fig:fits): the fits of the estimators of the main text on
# one-dimensional data. Each estimator is one job.

rule sim_fits:
    input:
        helpers=lambda wc: ESTIMATOR_CODE[wc.method] + DEMO,
    output:
        "results/fits/{method}.csv",
    wildcard_constraints:
        method="|".join(ESTIMATORS),
    threads: 1
    script: "py/sim_fits.py"


rule fig_fits:
    input:
        predictions=expand("results/fits/{method}.csv", method=PAPER_MAIN),
        helpers=DISPLAY,
    output:
        figure=f"{ART}/figures/fits.pdf",
        numbers=f"{ART}/numbers/fits.tex",
    params:
        methods=PAPER_MAIN,
        names=PAPER_NAMES,
    script: "py/fig_fits.py"


# ---------------------------------------------------------------------------
# Figure 2 (fig:convergence) and the noise sweep share one simulation, whose
# cells are (sigma, n). Figure 2 reads the cells at sigma = 0.1.

rule sim_convergence:
    input:
        helpers=SIM,
    output:
        "results/convergence/sigma{sigma}/n{n}.csv",
    threads: workflow.cores
    script: "py/sim_convergence.py"


rule fig_convergence:
    input:
        cells=expand("results/convergence/sigma{sigma}/n{n}.csv",
                     sigma=CONVERGENCE_SIGMA, n=CONVERGENCE_N),
        helpers=DISPLAY,
    output:
        f"{ART}/figures/convergence.pdf",
    script: "py/fig_convergence.py"


rule fig_noise_sweep:
    input:
        cells=expand("results/convergence/sigma{sigma}/n{n}.csv",
                     sigma=NOISE_SIGMA, n=CONVERGENCE_N),
        helpers=DISPLAY,
    output:
        f"{NOTES}/figures/noise-sweep.pdf",
    script: "py/fig_noise_sweep.py"


# ---------------------------------------------------------------------------
# The dimension sweep: HAR and mixed Sobolev KRR against the other methods the
# referee asked for, on two DGPs, as the number of covariates grows.

rule sim_dimension:
    input:
        helpers=SIM,
    output:
        "results/dimension/{dgp}/p{p}.csv",
    threads: workflow.cores
    script: "py/sim_dimension.py"


rule fig_dimension_sweep:
    input:
        cells=expand("results/dimension/{dgp}/p{p}.csv", dgp=DIMENSION_DGPS, p=DIMENSION_P),
        helpers=DISPLAY,
    output:
        f"{NOTES}/figures/dimension-sweep.pdf",
    script: "py/fig_dimension_sweep.py"


# ---------------------------------------------------------------------------
# notes/sobolev-mars.tex: Table 1, the time table and Figure 1 with the four
# added estimators (MORE) next to the nine of Section 4. The added fits are
# jobs of the same shape as the paper's, on one thread each, and they write
# results/ in the same layout, so the note's displays read the paper's fits as
# they stand.

SM_FITS = TABLE1_FITS + [(d, m) for d in TABLE1_DATASETS for m in MORE + DEPTH]


def sm_files(kind):
    """The result or tuning file of every fit that the note's tables read."""
    suffix = "" if kind == "result" else "-tuning"
    return [f"results/table1/{d}/{m}/rep{r}{suffix}.csv" for d, m in SM_FITS for r in TABLE1_REPS]


def _more_python(wc):
    """The interpreter of an added estimator's fits."""
    return MARS_PYTHON if wc.method == "mars" else sys.executable


rule table1_fit_more:
    input:
        data=f"{DATA}/{{dataset}}.csv",
        helpers=lambda wc: MORE_CODE[wc.method] + MORE_BASE + TABLE1_FIT,
    output:
        result="results/table1/{dataset}/{method}/rep{rep}.csv",
        tuning="results/table1/{dataset}/{method}/rep{rep}-tuning.csv",
    wildcard_constraints:
        method="|".join(MORE),
    params:
        python=_more_python,
    threads: 1
    shell:
        "{params.python} py/more_fits.py table1 {input.data} {wildcards.dataset} {wildcards.method}"
        " {wildcards.rep} {output.result} {output.tuning}"


rule sim_fits_more:
    input:
        helpers=lambda wc: MORE_CODE[wc.method] + MORE_BASE + DEMO,
    output:
        "results/fits/{method}.csv",
    wildcard_constraints:
        method="|".join(MORE),
    params:
        python=_more_python,
    threads: 1
    shell:
        "{params.python} py/more_fits.py fits {wildcards.method} {output}"


rule table1_fit_depth:
    input:
        data=f"{DATA}/{{dataset}}.csv",
        helpers=lambda wc: DEPTH_CODE[wc.method] + DEPTH_BASE + TABLE1_FIT,
    output:
        result="results/table1/{dataset}/{method}/rep{rep}.csv",
        tuning="results/table1/{dataset}/{method}/rep{rep}-tuning.csv",
    wildcard_constraints:
        method="|".join(DEPTH),
    threads: 1
    shell:
        f"{sys.executable} py/added_fits.py more_depth table1 {{input.data}} {{wildcards.dataset}}"
        " {wildcards.method} {wildcards.rep} {output.result} {output.tuning}"


rule sim_fits_depth:
    input:
        helpers=lambda wc: DEPTH_CODE[wc.method] + DEPTH_BASE + DEMO,
    output:
        "results/fits/{method}.csv",
    wildcard_constraints:
        method="|".join(DEPTH),
    threads: 1
    shell:
        f"{sys.executable} py/added_fits.py more_depth fits {{wildcards.method}} {{output}}"


rule sm_tables:
    input:
        results=sm_files("result"),
        tunings=sm_files("tuning"),
        helpers=DISPLAY,
    output:
        rmse=f"{NOTES}/tables/sobolev-mars-rmse.tex",
        runtime=f"{NOTES}/tables/sobolev-mars-runtime.tex",
        ratios=f"{NOTES}/tables/sobolev-mars-ratios.tex",
        numbers=f"{NOTES}/numbers/sobolev-mars.tex",
    params:
        datasets=TABLE1_DATASETS,
        methods=SM_METHODS,
        added=MORE + DEPTH,
    script: "py/sm_tables.py"


rule sm_fig_fits:
    input:
        predictions=expand("results/fits/{method}.csv", method=SM_METHODS),
        helpers=DISPLAY,
    output:
        figure=f"{NOTES}/figures/sobolev-mars-fits.pdf",
        numbers=f"{NOTES}/numbers/sobolev-mars-fits.tex",
    params:
        methods=SM_METHODS,
    script: "py/sm_fig_fits.py"
